from typing import Dict, List, Optional
from app.models.hotel import StayItem
from app.utils.geo import format_price_pkr, haversine_distance_km


CURATED_HOTELS_DB: List[Dict] = [
    # ─────────────────────────────────────────────────────────────────────────
    # ── ISLAMABAD & RAWALPINDI (11 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_isb_serena",
        "name": "Islamabad Serena Hotel",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 33.7167,
        "longitude": 73.1044,
        "city": "Islamabad",
        "short_address": "Club Road, Sector G-5/1",
        "full_address": "Khayaban-e-Suhrawardy, Sector G-5/1, Islamabad, 44000",
        "address": "Club Road, Sector G-5/1, Islamabad",
        "rating": 4.8,
        "reviews_count": 5200,
        "price_per_night_pkr": 65000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "Premier 5-star heritage luxury hotel surrounded by lush gardens beside Rawal Lake and the Margalla Hills.",
        "highlight": "5-Star Heritage Luxury",
        "amenities": ["Free High-Speed Wi-Fi", "Swimming Pool", "Spa & Wellness Center", "Fine Dining Restaurant", "Complimentary Breakfast", "Free Secure Parking"],
        "website": "https://www.serenahotels.com/islamabad",
        "phone": "+92 51 2874000",
    },
    {
        "id": "fallback_isb_marriott",
        "name": "Islamabad Marriott Hotel",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 33.7225,
        "longitude": 73.0850,
        "city": "Islamabad",
        "short_address": "Sector F-5/1",
        "full_address": "Agha Khan Rd, Shalimar 5, Sector F-5/1, Islamabad",
        "address": "Agha Khan Rd, Sector F-5/1, Islamabad",
        "rating": 4.6,
        "reviews_count": 4800,
        "price_per_night_pkr": 52000,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "description": "Distinguished luxury hotel situated in the heart of Islamabad near diplomatic enclave and Margalla trails.",
        "highlight": "Diplomatic Enclave Luxury",
        "amenities": ["Free High-Speed Wi-Fi", "Swimming Pool", "Spa & Wellness Center", "Fine Dining Restaurant", "Complimentary Breakfast", "24/7 Room Service"],
        "website": "https://www.marriott.com/isbpk",
        "phone": "+92 51 2826121",
    },
    {
        "id": "fallback_isb_ramada",
        "name": "Ramada by Wyndham Islamabad",
        "category": "luxury",
        "badge_label": "4-Star Luxury",
        "latitude": 33.7050,
        "longitude": 73.0980,
        "city": "Islamabad",
        "short_address": "Club Road, Rawal Lake",
        "full_address": "1 Club Road, Shakar Parian, Islamabad",
        "address": "1 Club Road, Shakar Parian, Islamabad",
        "rating": 4.4,
        "reviews_count": 3100,
        "price_per_night_pkr": 38000,
        "image_url": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
        "description": "Modern lakeside hotel featuring panoramic views of Rawal Lake, indoor pool, rooftop BBQ, and spa.",
        "highlight": "Rawal Lakefront Hotel",
        "amenities": ["Rawal Lake View", "Indoor Pool", "Rooftop Restaurant", "Free High-Speed Wi-Fi", "Fitness Center"],
        "website": "https://www.wyndhamhotels.com/ramada",
        "phone": "+92 51 111384384",
    },
    {
        "id": "fallback_isb_monal_treehouse",
        "name": "Highland Resort & Boutique Lodges",
        "category": "resort",
        "badge_label": "Mountain Resort",
        "latitude": 33.7915,
        "longitude": 73.1420,
        "city": "Islamabad",
        "short_address": "Pir Sohawa, Margalla Hills",
        "full_address": "Pir Sohawa Rd, Sangada, Islamabad Capital Territory",
        "address": "Pir Sohawa Rd, Margalla Hills, Islamabad",
        "rating": 4.5,
        "reviews_count": 2100,
        "price_per_night_pkr": 32000,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Perched high on the Margalla ridge with panoramic sunset views over Islamabad valley.",
        "highlight": "Panoramic Margalla Ridge",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Evening Bonfire Area", "Free Secure Parking", "Free High-Speed Wi-Fi"],
        "website": "https://www.highlandresort.com.pk",
        "phone": "+92 51 2806136",
    },
    {
        "id": "fallback_isb_whispering_pines",
        "name": "Whispering Pines Resort Margalla",
        "category": "resort",
        "badge_label": "Pine Forest Resort",
        "latitude": 33.8210,
        "longitude": 73.1550,
        "city": "Islamabad",
        "short_address": "Pir Sohawa Ridge",
        "full_address": "Pir Sohawa Road, Haripur-Islamabad Border, Margalla",
        "address": "Pir Sohawa Road, Margalla",
        "rating": 4.6,
        "reviews_count": 1400,
        "price_per_night_pkr": 36000,
        "image_url": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
        "description": "Exclusive alpine villas nestled inside dense pine forests overlooking misty valley gorges.",
        "highlight": "Pine Forest Serenity",
        "amenities": ["Pine Forest View", "Private Balconies", "Bonfire Pits", "Fine Dining", "Free Wi-Fi"],
        "website": "https://whisperingpinesresort.pk",
        "phone": "+92 300 5002758",
    },
    {
        "id": "fallback_isb_saidpur_heritage",
        "name": "Saidpur Heritage Haveli & Inn",
        "category": "boutique",
        "badge_label": "Heritage Lodge",
        "latitude": 33.7431,
        "longitude": 73.0682,
        "city": "Islamabad",
        "short_address": "Saidpur Village, Margalla Foothills",
        "full_address": "Main Street, Saidpur Historic Village, Islamabad",
        "address": "Saidpur Village, Sector F-6/4, Islamabad",
        "rating": 4.4,
        "reviews_count": 1250,
        "price_per_night_pkr": 19500,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Authentic stone-carved heritage inn preserving Mughal and colonial architectural charm.",
        "highlight": "Historic Mughal Village",
        "amenities": ["Village / Mountain View", "Traditional Courtyard", "Organic Desi Breakfast", "Free High-Speed Wi-Fi"],
        "website": "https://saidpurheritage.pk",
        "phone": "+92 51 2824310",
    },
    {
        "id": "fallback_isb_envoy",
        "name": "Envoy Continental Hotel",
        "category": "boutique",
        "badge_label": "Boutique Stay",
        "latitude": 33.7088,
        "longitude": 73.0560,
        "city": "Islamabad",
        "short_address": "Fazl-e-Haq Road, Blue Area",
        "full_address": "111-E Fazl-e-Haq Rd, G 7/3 Blue Area, Islamabad",
        "address": "Fazl-e-Haq Rd, Blue Area, Islamabad",
        "rating": 4.2,
        "reviews_count": 1850,
        "price_per_night_pkr": 14500,
        "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "description": "Comfortable corporate & family boutique hotel strategically located in the commercial heart of Islamabad.",
        "highlight": "Blue Area Commercial Hub",
        "amenities": ["City Center Access", "Complimentary Breakfast", "Free Wi-Fi", "Airport Shuttle Available"],
        "website": "https://www.envoycontinental.com",
        "phone": "+92 51 2277540",
    },
    {
        "id": "fallback_isb_margalla_hotel",
        "name": "Hotel Margala Islamabad",
        "category": "boutique",
        "badge_label": "Executive Boutique",
        "latitude": 33.7095,
        "longitude": 73.0870,
        "city": "Islamabad",
        "short_address": "M-2, Shahrah-e-Kashmir, G-5/2",
        "full_address": "M-2 Shahrah-e-Kashmir, near Convention Centre, Islamabad",
        "address": "Shahrah-e-Kashmir, G-5/2, Islamabad",
        "rating": 4.3,
        "reviews_count": 2200,
        "price_per_night_pkr": 16500,
        "image_url": "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80",
        "description": "Established executive hotel near the Convention Centre with landscaped gardens and multi-cuisine restaurant.",
        "highlight": "Convention Center Vicinity",
        "amenities": ["Garden Lawn", "Conference Facilities", "Free Wi-Fi", "Complimentary Breakfast"],
        "website": "https://hotelmargala.com",
        "phone": "+92 51 2276500",
    },
    {
        "id": "fallback_isb_glamping",
        "name": "Margalla Glamping Pods & Campsite",
        "category": "glamping",
        "badge_label": "Campsite / Pods",
        "latitude": 33.7745,
        "longitude": 73.0780,
        "city": "Islamabad",
        "short_address": "Pir Sohawa Foothills, Margalla",
        "full_address": "Pir Sohawa Foothills Nature Reserve, Margalla Hills National Park, Islamabad",
        "address": "Pir Sohawa Road, Margalla, Islamabad",
        "rating": 4.7,
        "reviews_count": 890,
        "price_per_night_pkr": 12000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Eco-friendly wooden glamping domes nestled under pine trees with stargazing decks and campfire pits.",
        "highlight": "Stargazing Nature Glamping",
        "amenities": ["Private Stargazing Deck", "Campfire & BBQ Pit", "Solar Power Setup", "Guided Nature Hikes"],
        "website": "https://margallaglamping.pk",
        "phone": "+92 301 8501234",
    },
    {
        "id": "fallback_isb_crown_plaza",
        "name": "Hotel Crown Plaza Islamabad",
        "category": "budget",
        "badge_label": "Comfort Stay",
        "latitude": 33.7120,
        "longitude": 73.0610,
        "city": "Islamabad",
        "short_address": "Jinnah Avenue, Blue Area",
        "full_address": "99-E Jinnah Avenue, Blue Area, Islamabad",
        "address": "Jinnah Avenue, Blue Area, Islamabad",
        "rating": 4.1,
        "reviews_count": 1600,
        "price_per_night_pkr": 9800,
        "image_url": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "description": "Modern budget-friendly city hotel with central air conditioning, free Wi-Fi, and quick metro access.",
        "highlight": "Metro Bus Accessible",
        "amenities": ["Free High-Speed Wi-Fi", "Complimentary Breakfast", "24/7 Front Desk", "Elevator Access"],
        "website": "https://hotelcrownplaza.com.pk",
        "phone": "+92 51 2278001",
    },
    {
        "id": "fallback_isb_backpacker_hostel",
        "name": "Islamabad Backpacker & Travelers Lodge",
        "category": "budget",
        "badge_label": "Budget Hostel",
        "latitude": 33.7250,
        "longitude": 73.0550,
        "city": "Islamabad",
        "short_address": "Sector F-7/1",
        "full_address": "Street 18, Sector F-7/1, Islamabad",
        "address": "Street 18, Sector F-7/1, Islamabad",
        "rating": 4.3,
        "reviews_count": 950,
        "price_per_night_pkr": 4500,
        "image_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
        "description": "Cozy and secure backpacker haven close to Jinnah Super Market with shared lounge and rooftop tea terrace.",
        "highlight": "Jinnah Super Market Proximity",
        "amenities": ["Free Wi-Fi", "Shared Kitchenette", "Rooftop Terrace", "Bicycle Rental"],
        "website": "https://isbbackpacker.pk",
        "phone": "+92 333 5123987",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── LAHORE (10 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_lhr_pc",
        "name": "Pearl Continental Hotel Lahore",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 31.5451,
        "longitude": 74.3381,
        "city": "Lahore",
        "short_address": "Shahrah-e-Quaid-e-Azam",
        "full_address": "Shahrah-e-Quaid-e-Azam, G.O.R. - I, Lahore, 54000",
        "address": "Shahrah-e-Quaid-e-Azam, Mall Road, Lahore",
        "rating": 4.7,
        "reviews_count": 6800,
        "price_per_night_pkr": 48000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "Lahore's premier heritage luxury hotel, famed for hospitality, multi-cuisine dining, and central location.",
        "highlight": "Mall Road Grand Heritage",
        "amenities": ["Outdoor Heated Pool", "Signature Spa", "Multiple Fine Dining Outlets", "Executive Lounge", "Free Secure Parking"],
        "website": "https://www.pchotels.com/pclahore",
        "phone": "+92 42 111505505",
    },
    {
        "id": "fallback_lhr_nishat_gulberg",
        "name": "The Nishat Hotel Gulberg",
        "category": "luxury",
        "badge_label": "5-Star Boutique",
        "latitude": 31.5126,
        "longitude": 74.3541,
        "city": "Lahore",
        "short_address": "Mian Mehmood Ali Kasoori Rd, Gulberg III",
        "full_address": "9A Mian Mehmood Ali Kasoori Rd, Block A3, Gulberg III, Lahore",
        "address": "Mian Mehmood Ali Kasoori Rd, Gulberg III, Lahore",
        "rating": 4.8,
        "reviews_count": 4200,
        "price_per_night_pkr": 54000,
        "image_url": "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
        "description": "Ultra-luxury Parisian boutique hotel with custom Italian marble suites, indoor pool, and world-class spa.",
        "highlight": "Gulberg Haute Luxury",
        "amenities": ["Indoor Heated Pool", "Luxury Wellness Spa", "Italian Dining", "Valet Parking", "Free High-Speed Wi-Fi"],
        "website": "https://nishathotel.biz",
        "phone": "+92 42 111646835",
    },
    {
        "id": "fallback_lhr_avari",
        "name": "Avari Hotel Lahore",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 31.5540,
        "longitude": 74.3310,
        "city": "Lahore",
        "short_address": "Mall Road, Lahore",
        "full_address": "87 Mall Road, Jubilee Town, Lahore",
        "address": "87 Mall Road, Lahore",
        "rating": 4.6,
        "reviews_count": 5100,
        "price_per_night_pkr": 42000,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "description": "Iconic luxury hotel surrounded by landscaped gardens with outdoor pool, Japanese cuisine, and live entertainment.",
        "highlight": "Historic Mall Road Estate",
        "amenities": ["Outdoor Swimming Pool", "Japanese & Chinese Restaurants", "Health Club", "Free Wi-Fi", "Free Valet"],
        "website": "https://www.avari.com/lahore",
        "phone": "+92 42 36366366",
    },
    {
        "id": "fallback_lhr_falettis",
        "name": "Faletti's Hotel Lahore",
        "category": "boutique",
        "badge_label": "Colonial Heritage",
        "latitude": 31.5605,
        "longitude": 74.3295,
        "city": "Lahore",
        "short_address": "Egerton Road",
        "full_address": "24 Egerton Road, Jubilee Town, Lahore",
        "address": "Egerton Road, Lahore",
        "rating": 4.5,
        "reviews_count": 3400,
        "price_per_night_pkr": 28000,
        "image_url": "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=1200&q=80",
        "description": "Dating to 1880, this colonial heritage jewel features suites once occupied by historical luminaries.",
        "highlight": "1880 Historic Heritage",
        "amenities": ["Colonial High Tea Lawn", "Historic Heritage Suites", "Fine Dining", "Free High-Speed Wi-Fi"],
        "website": "https://falettishotel.com",
        "phone": "+92 42 36363063",
    },
    {
        "id": "fallback_lhr_luxus_grand",
        "name": "Luxus Grand Hotel Lahore",
        "category": "boutique",
        "badge_label": "City Boutique",
        "latitude": 31.5510,
        "longitude": 74.3210,
        "city": "Lahore",
        "short_address": "Egerton Rd, near Punjab Assembly",
        "full_address": "4 Egerton Rd, Jubilee Town, Lahore",
        "address": "Egerton Rd, Jubilee Town, Lahore",
        "rating": 4.4,
        "reviews_count": 2800,
        "price_per_night_pkr": 22000,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Elegant modern boutique hotel featuring cinema lounge, heated pool, and rooftop buffet dining.",
        "highlight": "Downtown Cinema & Pool",
        "amenities": ["Indoor Heated Pool", "Private Cinema Lounge", "Free Wi-Fi", "Complimentary Breakfast"],
        "website": "https://luxusgrand.com",
        "phone": "+92 42 36371111",
    },
    {
        "id": "fallback_lhr_heritage_suites",
        "name": "Heritage Luxury Suites Gulberg",
        "category": "resort",
        "badge_label": "Luxury Suites",
        "latitude": 31.5170,
        "longitude": 74.3500,
        "city": "Lahore",
        "short_address": "Gulberg II, near MM Alam Rd",
        "full_address": "Block C-2, Gulberg II, Lahore",
        "address": "Gulberg II, Lahore",
        "rating": 4.5,
        "reviews_count": 1900,
        "price_per_night_pkr": 24000,
        "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "description": "Spacious luxury residential suites with private kitchens and executive services near MM Alam Road.",
        "highlight": "MM Alam Fashion District",
        "amenities": ["Full Suite Kitchenette", "Gym & Sauna", "Free Wi-Fi", "Complimentary Breakfast"],
        "website": "https://heritageluxurysuites.com",
        "phone": "+92 42 35750201",
    },
    {
        "id": "fallback_lhr_glamping_oasis",
        "name": "Lahore Glamping Oasis & Country Club",
        "category": "glamping",
        "badge_label": "Glamping Resort",
        "latitude": 31.4200,
        "longitude": 74.4500,
        "city": "Lahore",
        "short_address": "Bedian Road Farmhouses",
        "full_address": "Bedian Road Country Retreats, Lahore Outskirts",
        "address": "Bedian Road, Lahore",
        "rating": 4.6,
        "reviews_count": 920,
        "price_per_night_pkr": 18000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Luxury safari tents with private plunge pools, organic orchards, and horse riding in suburban Lahore.",
        "highlight": "Safari Tents & Horse Riding",
        "amenities": ["Private Plunge Pool", "Horse Riding Track", "Bonfire & BBQ", "Organic Farm Breakfast"],
        "website": "https://lahoreglamping.pk",
        "phone": "+92 300 4567890",
    },
    {
        "id": "fallback_lhr_park_lane",
        "name": "Park Lane Hotel Lahore",
        "category": "boutique",
        "badge_label": "Boutique Stay",
        "latitude": 31.5140,
        "longitude": 74.3490,
        "city": "Lahore",
        "short_address": "MM Alam Road, Gulberg III",
        "full_address": "107 MM Alam Rd, Block B3, Gulberg III, Lahore",
        "address": "MM Alam Rd, Gulberg III, Lahore",
        "rating": 4.3,
        "reviews_count": 1650,
        "price_per_night_pkr": 16000,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Stylish hotel right on MM Alam dining strip, offering comfortable modern rooms and quick airport link.",
        "highlight": "Dining District Heart",
        "amenities": ["Rooftop Restaurant", "Free Wi-Fi", "Complimentary Breakfast", "Airport Shuttle"],
        "website": "https://parklanehotel.pk",
        "phone": "+92 42 35777777",
    },
    {
        "id": "fallback_lhr_rose_palace",
        "name": "Rose Palace Hotel Gulberg",
        "category": "budget",
        "badge_label": "Budget Stay",
        "latitude": 31.5200,
        "longitude": 74.3450,
        "city": "Lahore",
        "short_address": "Gulberg III",
        "full_address": "55 N Block, Gulberg III, Lahore",
        "address": "Gulberg III, Lahore",
        "rating": 4.1,
        "reviews_count": 1400,
        "price_per_night_pkr": 7500,
        "image_url": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "description": "Reliable budget accommodation in central Gulberg with clean rooms, air conditioning, and room service.",
        "highlight": "Affordable Gulberg Base",
        "amenities": ["Free Wi-Fi", "Air Conditioning", "Complimentary Breakfast", "24/7 Front Desk"],
        "website": "https://rosepalacehotel.com.pk",
        "phone": "+92 42 35758000",
    },
    {
        "id": "fallback_lhr_hotel_one",
        "name": "Hotel One Downtown Lahore",
        "category": "budget",
        "badge_label": "Budget Choice",
        "latitude": 31.5380,
        "longitude": 74.3250,
        "city": "Lahore",
        "short_address": "Davis Road",
        "full_address": "Davis Road, near Mall Road, Lahore",
        "address": "Davis Road, Lahore",
        "rating": 4.2,
        "reviews_count": 1950,
        "price_per_night_pkr": 9200,
        "image_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
        "description": "Hashoo Group budget property with consistent standards, fresh linen, and proximity to railway station.",
        "highlight": "Central Transit Hub",
        "amenities": ["Free Wi-Fi", "Complimentary Breakfast", "24/7 Room Service", "Secure Parking"],
        "website": "https://www.hotelone.com.pk",
        "phone": "+92 42 111111663",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── KARACHI (9 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_khi_marriott",
        "name": "Karachi Marriott Hotel",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 24.8485,
        "longitude": 67.0260,
        "city": "Karachi",
        "short_address": "Abdullah Haroon Road, Civil Lines",
        "full_address": "9 Abdullah Haroon Rd, Civil Lines, Karachi, 75530",
        "address": "Abdullah Haroon Rd, Civil Lines, Karachi",
        "rating": 4.6,
        "reviews_count": 5600,
        "price_per_night_pkr": 46000,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "description": "Prestigious 5-star hotel in Karachi's consular district featuring outdoor pool, luxury spa, and Chinese bistro.",
        "highlight": "Consular District 5-Star",
        "amenities": ["Outdoor Swimming Pool", "Spa & Wellness Center", "Executive Lounge", "Free High-Speed Wi-Fi", "Complimentary Breakfast"],
        "website": "https://www.marriott.com/khipk",
        "phone": "+92 21 111223344",
    },
    {
        "id": "fallback_khi_pc",
        "name": "Pearl Continental Hotel Karachi",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 24.8465,
        "longitude": 67.0298,
        "city": "Karachi",
        "short_address": "Club Road, Civil Lines",
        "full_address": "Club Rd, Civil Lines, Karachi, 75530",
        "address": "Club Rd, Civil Lines, Karachi",
        "rating": 4.5,
        "reviews_count": 4900,
        "price_per_night_pkr": 44000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "Landmark Karachi hotel boasting legendary dining outlets, outdoor pool, and executive ballroom suites.",
        "highlight": "Flagship Commercial Hub",
        "amenities": ["Outdoor Pool", "Multiple Fine Dining Restaurants", "Health Club", "Free Valet Parking", "Free Wi-Fi"],
        "website": "https://www.pchotels.com/pckarachi",
        "phone": "+92 21 111505505",
    },
    {
        "id": "fallback_khi_movenpick",
        "name": "Mövenpick Hotel Karachi",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 24.8510,
        "longitude": 67.0280,
        "city": "Karachi",
        "short_address": "Club Road",
        "full_address": "Club Rd, Civil Lines, Karachi",
        "address": "Club Rd, Karachi",
        "rating": 4.6,
        "reviews_count": 4100,
        "price_per_night_pkr": 45000,
        "image_url": "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
        "description": "Swiss hospitality in the heart of Karachi with outdoor heated pool, Lebanese dining, and signature chocolate hour.",
        "highlight": "Swiss Luxury & Dining",
        "amenities": ["Swimming Pool", "Signature Chocolate Hour", "Spa", "Free Wi-Fi", "Complimentary Breakfast"],
        "website": "https://movenpick.accor.com/karachi",
        "phone": "+92 21 35633333",
    },
    {
        "id": "fallback_khi_beach_luxury",
        "name": "Beach Luxury Hotel Waterfront",
        "category": "resort",
        "badge_label": "Coastal Resort",
        "latitude": 24.8410,
        "longitude": 66.9980,
        "city": "Karachi",
        "short_address": "Moulvi Tamizuddin Khan Rd",
        "full_address": "MT Khan Rd, Lalazar, Karachi",
        "address": "MT Khan Rd, Karachi",
        "rating": 4.3,
        "reviews_count": 3200,
        "price_per_night_pkr": 21000,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Waterfront resort hotel surrounded by mangrove creeks, lush coconut palms, and open-air seaside dining.",
        "highlight": "Mangrove Creek Waterfront",
        "amenities": ["Seaside Creek View", "Outdoor Pool", "Open-Air Lawn Dining", "Free Wi-Fi"],
        "website": "https://beachluxuryhotel.com",
        "phone": "+92 21 35611031",
    },
    {
        "id": "fallback_khi_glamping_coastal",
        "name": "Turtle Beach Glamping Huts & Pods",
        "category": "glamping",
        "badge_label": "Coastal Glamping",
        "latitude": 24.8150,
        "longitude": 66.8650,
        "city": "Karachi",
        "short_address": "Hawkesbay Turtle Beach",
        "full_address": "Turtle Beach, Hawkesbay Coastal Strip, Karachi",
        "address": "Hawkesbay, Karachi",
        "rating": 4.7,
        "reviews_count": 820,
        "price_per_night_pkr": 22000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Exclusive beachfront glamping huts on golden sands with private sundecks, beach bonfires, and turtle watching.",
        "highlight": "Arabian Sea Beachfront",
        "amenities": ["Direct Beach Access", "Private Sundeck", "Seafood BBQ Bonfire", "Turtle Watching Tours"],
        "website": "https://turtlebeachglamping.pk",
        "phone": "+92 300 2345678",
    },
    {
        "id": "fallback_khi_excelsior",
        "name": "Hotel Excelsior Karachi",
        "category": "boutique",
        "badge_label": "City Boutique",
        "latitude": 24.8560,
        "longitude": 67.0180,
        "city": "Karachi",
        "short_address": "Sarwar Shaheed Road, Saddar",
        "full_address": "Sarwar Shaheed Rd, Saddar, Karachi",
        "address": "Saddar, Karachi",
        "rating": 4.2,
        "reviews_count": 1500,
        "price_per_night_pkr": 14000,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Modern downtown boutique hotel situated in Saddar, close to Empress Market and historic heritage architecture.",
        "highlight": "Historic Saddar Proximity",
        "amenities": ["Free Wi-Fi", "Complimentary Breakfast", "Airport Shuttle", "24/7 Concierge"],
        "website": "https://hotelexcelsiorkarachi.com",
        "phone": "+92 21 35630011",
    },
    {
        "id": "fallback_khi_embassy_inn",
        "name": "Embassy Inn Hotel Karachi",
        "category": "budget",
        "badge_label": "Budget Stay",
        "latitude": 24.8680,
        "longitude": 67.0620,
        "city": "Karachi",
        "short_address": "Shahrah-e-Faisal",
        "full_address": "100-B Shahrah-e-Faisal, Block 6 PECHS, Karachi",
        "address": "Shahrah-e-Faisal, Karachi",
        "rating": 4.1,
        "reviews_count": 1750,
        "price_per_night_pkr": 8800,
        "image_url": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "description": "Conveniently situated on the Shahrah-e-Faisal expressway, offering clean AC rooms and speedy airport commute.",
        "highlight": "Expressway Transit Corridor",
        "amenities": ["Free Wi-Fi", "Air Conditioning", "Complimentary Breakfast", "Free Parking"],
        "website": "https://embassyinn.com.pk",
        "phone": "+92 21 34535871",
    },
    {
        "id": "fallback_khi_days_inn",
        "name": "Days Inn by Wyndham Karachi",
        "category": "budget",
        "badge_label": "Economy Comfort",
        "latitude": 24.8620,
        "longitude": 67.0700,
        "city": "Karachi",
        "short_address": "PECHS Block 6",
        "full_address": "Block 6 PECHS, Karachi",
        "address": "PECHS, Karachi",
        "rating": 4.2,
        "reviews_count": 1100,
        "price_per_night_pkr": 9500,
        "image_url": "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
        "description": "International economy hotel brand with dependable comfort, hot breakfast, and business meeting rooms.",
        "highlight": "Wyndham Economy Quality",
        "amenities": ["Free Wi-Fi", "Complimentary Breakfast", "24/7 Front Desk", "Meeting Facilities"],
        "website": "https://www.wyndhamhotels.com/days-inn",
        "phone": "+92 21 34542200",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── HUNZA & GILGIT (9 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_hnz_luxus",
        "name": "Luxus Hunza Attabad Lake Resort",
        "category": "resort",
        "badge_label": "Mountain Resort",
        "latitude": 36.3350,
        "longitude": 74.8620,
        "city": "Hunza",
        "short_address": "Attabad Lake Waterfront, Gojal",
        "full_address": "Attabad Lake Waterfront, Karakoram Hwy, Ainabad, Hunza",
        "address": "Attabad Lake Waterfront, Hunza",
        "rating": 4.9,
        "reviews_count": 2800,
        "price_per_night_pkr": 62000,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "description": "Superb 5-star mountain sanctuary with floor-to-ceiling glass balconies overlooking the turquoise Attabad Lake.",
        "highlight": "Turquoise Lakefront Glaze",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Evening Bonfire Area", "Complimentary Breakfast", "Jeep & Tour Desk", "Free High-Speed Wi-Fi"],
        "website": "https://luxushunza.com",
        "phone": "+92 5813 456789",
    },
    {
        "id": "fallback_hnz_serena",
        "name": "Hunza Serena Inn Karimabad",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 36.3262,
        "longitude": 74.6644,
        "city": "Hunza",
        "short_address": "Karimabad Valley",
        "full_address": "Karimabad, Hunza District, Gilgit-Baltistan",
        "address": "Karimabad, Hunza",
        "rating": 4.8,
        "reviews_count": 3100,
        "price_per_night_pkr": 48000,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Authentic Hunza architecture surrounded by apricot orchards facing the majestic Rakaposhi and Ultar Sar peaks.",
        "highlight": "Rakaposhi Glacier Panorama",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Complimentary Breakfast", "Evening Bonfire Area", "Jeep & Tour Desk"],
        "website": "https://www.serenahotels.com/hunza-serena-inn",
        "phone": "+92 5813 457600",
    },
    {
        "id": "fallback_hnz_eagles_nest",
        "name": "Eagle's Nest Hotel Duikar",
        "category": "resort",
        "badge_label": "Panoramic Lodge",
        "latitude": 36.3290,
        "longitude": 74.6910,
        "city": "Hunza",
        "short_address": "Duikar Ridge (2,850m)",
        "full_address": "Duikar Heights, Karimabad, Hunza",
        "address": "Duikar Heights, Hunza",
        "rating": 4.7,
        "reviews_count": 2100,
        "price_per_night_pkr": 32000,
        "image_url": "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
        "description": "Situated at the highest viewpoint in Hunza, providing breathtaking 360-degree vistas of 8 mountain peaks.",
        "highlight": "Highest Viewpoint in Hunza",
        "amenities": ["360 Mountain Views", "Rooftop Restaurant", "Campfire Nights", "Free Wi-Fi"],
        "website": "https://eaglesnesthunza.com",
        "phone": "+92 5813 457582",
    },
    {
        "id": "fallback_hnz_glamping",
        "name": "Hunza Glamping Pods & Stargazing Domes",
        "category": "glamping",
        "badge_label": "Campsite / Pods",
        "latitude": 36.3120,
        "longitude": 74.6850,
        "city": "Hunza",
        "short_address": "Duikar Eagle's Nest Ridge",
        "full_address": "Eagle's Nest Rd, Duikar, Karimabad, Hunza",
        "address": "Duikar, Karimabad, Hunza",
        "rating": 4.7,
        "reviews_count": 890,
        "price_per_night_pkr": 26000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "High-altitude geodome pods offering 360-degree sunrise views over 7,000-meter snowcapped giants.",
        "highlight": "Duikar Sunrise Stargazer",
        "amenities": ["Mountain / Valley View", "Evening Bonfire Area", "Jeep & Tour Desk", "Central Heating & AC"],
        "website": "https://hunzaglamping.com",
        "phone": "+92 345 5567890",
    },
    {
        "id": "fallback_hnz_darbar",
        "name": "Darbar Hotel Hunza",
        "category": "boutique",
        "badge_label": "Mountain Boutique",
        "latitude": 36.3180,
        "longitude": 74.6520,
        "city": "Hunza",
        "short_address": "Aliabad, Hunza",
        "full_address": "Karakoram Highway, Aliabad, Hunza",
        "address": "Aliabad, Hunza",
        "rating": 4.4,
        "reviews_count": 1400,
        "price_per_night_pkr": 18500,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Traditional stone-walled alpine hotel with panoramic Rakaposhi views and organic local culinary specialties.",
        "highlight": "Rakaposhi Roadside Oasis",
        "amenities": ["Mountain View", "Traditional Desi Restaurant", "Free Wi-Fi", "Free Parking"],
        "website": "https://darbarhunza.pk",
        "phone": "+92 5813 455020",
    },
    {
        "id": "fallback_hnz_budget",
        "name": "Old Hunza Inn & Trekker Lodge",
        "category": "budget",
        "badge_label": "Guest House / Budget",
        "latitude": 36.3240,
        "longitude": 74.6600,
        "city": "Hunza",
        "short_address": "Bazaar Rd, Karimabad",
        "full_address": "Bazaar Rd, Karimabad, Hunza, Gilgit-Baltistan",
        "address": "Bazaar Rd, Karimabad, Hunza",
        "rating": 4.3,
        "reviews_count": 680,
        "price_per_night_pkr": 6500,
        "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "description": "Warm, family-run mountaineer guest lodge offering homemade walnut cakes, hot showers, and trekking guides.",
        "highlight": "Friendly Trekker Haven",
        "amenities": ["Mountain / Valley View", "Free High-Speed Wi-Fi", "Complimentary Breakfast", "Jeep & Tour Desk"],
        "website": "https://oldhunzainn.pk",
        "phone": "+92 5813 457002",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── SKARDU & BALTISTAN (8 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_skd_shangrila",
        "name": "Shangrila Resort Kachura Skardu",
        "category": "resort",
        "badge_label": "Mountain Resort",
        "latitude": 35.4244,
        "longitude": 75.4501,
        "city": "Skardu",
        "short_address": "Lower Kachura Lake",
        "full_address": "Shangrila Resort, Lower Kachura Lake, Skardu, 16100",
        "address": "Lower Kachura Lake, Skardu",
        "rating": 4.8,
        "reviews_count": 3600,
        "price_per_night_pkr": 48000,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "description": "Legendary 'Heaven on Earth' resort surrounding the heart-shaped Kachura Lake with pagodas and flower gardens.",
        "highlight": "Heart-Shaped Kachura Lake",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Complimentary Breakfast", "Jeep & Tour Desk", "Free High-Speed Wi-Fi", "Free Secure Parking"],
        "website": "https://www.shangrilaresorts.com.pk",
        "phone": "+92 5815 454941",
    },
    {
        "id": "fallback_skd_shigar",
        "name": "Serena Shigar Fort Palace",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 35.4255,
        "longitude": 75.7275,
        "city": "Skardu",
        "short_address": "Shigar Valley",
        "full_address": "Shigar Fort, Shigar Valley, Skardu, Gilgit-Baltistan",
        "address": "Shigar Valley, Skardu",
        "rating": 4.9,
        "reviews_count": 2900,
        "price_per_night_pkr": 56000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "400-year-old Raja palace restored into an exquisite 5-star living museum hotel with historic royal gardens.",
        "highlight": "400-Yr Royal Fort Heritage",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Complimentary Breakfast", "Historic Royal Museum", "Free Secure Parking"],
        "website": "https://www.serenahotels.com/serena-shigar-fort",
        "phone": "+92 5815 460100",
    },
    {
        "id": "fallback_skd_khaplu",
        "name": "Serena Khaplu Palace",
        "category": "luxury",
        "badge_label": "Heritage Royal Palace",
        "latitude": 35.1550,
        "longitude": 76.3350,
        "city": "Skardu",
        "short_address": "Khaplu Valley, Ghanche",
        "full_address": "Khaplu Palace, Khaplu, Ghanche District, Gilgit-Baltistan",
        "address": "Khaplu Valley, Skardu",
        "rating": 4.9,
        "reviews_count": 2100,
        "price_per_night_pkr": 52000,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "description": "Magnificent Yabgo royal residence restored by Aga Khan Cultural Service, offering serene apricot gardens.",
        "highlight": "Historic Royal Residence",
        "amenities": ["Royal Gardens", "Traditional Dining", "Museum Tour", "Free Wi-Fi", "Free Breakfast"],
        "website": "https://www.serenahotels.com/serena-khaplu-palace",
        "phone": "+92 5816 450141",
    },
    {
        "id": "fallback_skd_sarfaranga_glamping",
        "name": "Sarfaranga Cold Desert Glamping Pods",
        "category": "glamping",
        "badge_label": "Desert Glamping",
        "latitude": 35.3450,
        "longitude": 75.6020,
        "city": "Skardu",
        "short_address": "Sarfaranga Cold Desert, Shigar Rd",
        "full_address": "Sarfaranga Sand Dunes, Skardu",
        "address": "Sarfaranga Desert, Skardu",
        "rating": 4.8,
        "reviews_count": 980,
        "price_per_night_pkr": 24000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Futuristic geodomes on high-altitude white sand dunes surrounded by Karakoram giants and starry skies.",
        "highlight": "World's Highest Cold Desert",
        "amenities": ["Stargazing Domes", "Desert Bonfires", "Quad Biking Access", "Solar Power"],
        "website": "https://sarfarangaglamping.pk",
        "phone": "+92 345 9876543",
    },
    {
        "id": "fallback_skd_byrsa",
        "name": "Byrsa Hotel Skardu City",
        "category": "boutique",
        "badge_label": "Alpine Boutique",
        "latitude": 35.2980,
        "longitude": 75.6350,
        "city": "Skardu",
        "short_address": "Airport Road, Skardu",
        "full_address": "Airport Road, near Skardu Bazaar",
        "address": "Airport Rd, Skardu",
        "rating": 4.4,
        "reviews_count": 1300,
        "price_per_night_pkr": 16000,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Modern comfort hotel with heated rooms, buffet restaurant, and direct transit to Deosai Plains.",
        "highlight": "Gateway to Deosai Plains",
        "amenities": ["Central Heating", "Buffet Dining", "Jeep Hire Desk", "Free Wi-Fi"],
        "website": "https://byrsahotel.pk",
        "phone": "+92 5815 450022",
    },
    {
        "id": "fallback_skd_budget",
        "name": "Baltistan Continental Hotel Skardu",
        "category": "budget",
        "badge_label": "Economy Comfort",
        "latitude": 35.2910,
        "longitude": 75.6400,
        "city": "Skardu",
        "short_address": "Main Bazaar Road",
        "full_address": "Main Bazaar Road, Skardu City",
        "address": "Main Bazaar, Skardu",
        "rating": 4.2,
        "reviews_count": 780,
        "price_per_night_pkr": 7500,
        "image_url": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
        "description": "Affordable alpine mountaineer stopover with warm hot water, clean beds, and local Balti meals.",
        "highlight": "Mountaineer Waypoint",
        "amenities": ["Hot Water 24/7", "Local Balti Food", "Free Wi-Fi", "Tour Assistance"],
        "website": "https://baltistancontinental.pk",
        "phone": "+92 5815 452233",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── SWAT / KALAM / MALAM JABBA (8 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_swt_pc_malam_jabba",
        "name": "Pearl Continental Hotel Malam Jabba",
        "category": "luxury",
        "badge_label": "5-Star Ski Resort",
        "latitude": 34.7980,
        "longitude": 72.5710,
        "city": "Swat / Kalam",
        "short_address": "Malam Jabba Ski Resort (2,800m)",
        "full_address": "Malam Jabba Ski Heights, Swat, Khyber Pakhtunkhwa",
        "address": "Malam Jabba, Swat",
        "rating": 4.8,
        "reviews_count": 3400,
        "price_per_night_pkr": 54000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "Pakistan's premier ski resort hotel with chairlift access, panoramic snow peak views, and heated indoor amenities.",
        "highlight": "Pakistan Premier Ski Resort",
        "amenities": ["Ski & Chairlift Access", "Heated Indoor Lounge", "Fine Dining", "Spa", "Free Wi-Fi"],
        "website": "https://www.pchotels.com/pcmalamjabba",
        "phone": "+92 946 755123",
    },
    {
        "id": "fallback_swt_serena",
        "name": "Swat Serena Hotel Saidu Sharif",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 34.7505,
        "longitude": 72.3582,
        "city": "Swat / Kalam",
        "short_address": "Club Road, Saidu Sharif",
        "full_address": "Club Rd, Opposite Golf Course, Saidu Sharif, Swat",
        "address": "Club Rd, Saidu Sharif, Swat",
        "rating": 4.7,
        "reviews_count": 2200,
        "price_per_night_pkr": 42000,
        "image_url": "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80",
        "description": "Colonial elegance with manicured rose gardens and historic royal suites in the valley of Swat.",
        "highlight": "Royal Swat Estate",
        "amenities": ["Free High-Speed Wi-Fi", "Swimming Pool", "Fine Dining Restaurant", "Complimentary Breakfast", "Free Secure Parking"],
        "website": "https://www.serenahotels.com/swat-serena-hotel",
        "phone": "+92 946 711640",
    },
    {
        "id": "fallback_swt_walnut",
        "name": "Walnut Heights Kalam Resort",
        "category": "resort",
        "badge_label": "Mountain Resort",
        "latitude": 35.4950,
        "longitude": 72.5920,
        "city": "Swat / Kalam",
        "short_address": "Jalban Kalam Valley",
        "full_address": "Walnut Forest Rd, Jalban, Kalam, Swat",
        "address": "Jalban, Kalam, Swat",
        "rating": 4.8,
        "reviews_count": 1400,
        "price_per_night_pkr": 38000,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "description": "Swiss-chalet style cedarwood resort surrounded by ancient walnut trees and crystalline river rapids.",
        "highlight": "Cedar Chalet by Ushu River",
        "amenities": ["Mountain / Valley View", "Fine Dining Restaurant", "Evening Bonfire Area", "Complimentary Breakfast", "Jeep & Tour Desk"],
        "website": "https://walnutheightskalam.com",
        "phone": "+92 300 8506789",
    },
    {
        "id": "fallback_swt_glamping",
        "name": "Kalam Pine Meadows Glamping Pods",
        "category": "glamping",
        "badge_label": "Alpine Glamping",
        "latitude": 35.5120,
        "longitude": 72.5850,
        "city": "Swat / Kalam",
        "short_address": "Ushu Forest Road, Kalam",
        "full_address": "Ushu Forest Glades, Kalam Valley, Swat",
        "address": "Ushu Forest, Kalam",
        "rating": 4.7,
        "reviews_count": 750,
        "price_per_night_pkr": 19000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Cozy pine-wood glamping cabins along the crystal clear Swat river with trout fishing and bonfire spots.",
        "highlight": "Pine Forest Trout Stream",
        "amenities": ["Riverfront Deck", "Trout Fishing", "Campfire & BBQ", "Solar Power"],
        "website": "https://kalamglamping.pk",
        "phone": "+92 312 3456789",
    },
    {
        "id": "fallback_swt_rock_city",
        "name": "Rock City Resort Fizagat Swat",
        "category": "boutique",
        "badge_label": "Valley View Boutique",
        "latitude": 34.8120,
        "longitude": 72.3780,
        "city": "Swat / Kalam",
        "short_address": "Fizagat, Mingora",
        "full_address": "Fizagat Hilltop, Mingora, Swat",
        "address": "Fizagat, Mingora, Swat",
        "rating": 4.4,
        "reviews_count": 1800,
        "price_per_night_pkr": 16500,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Perched on a cliff overlooking the roaring Swat River with open-air terrace dining and adventure tours.",
        "highlight": "Fizagat Cliffside Panorama",
        "amenities": ["River & Valley View", "Open-Air Restaurant", "Free Wi-Fi", "Free Parking"],
        "website": "https://rockcityresort.pk",
        "phone": "+92 946 720088",
    },
    {
        "id": "fallback_swt_budget",
        "name": "Golden Star Hotel Kalam",
        "category": "budget",
        "badge_label": "Budget Alpine Lodge",
        "latitude": 35.4880,
        "longitude": 72.5890,
        "city": "Swat / Kalam",
        "short_address": "Main Bazaar Kalam",
        "full_address": "Main Bazaar, Kalam Valley, Swat",
        "address": "Kalam Bazaar, Swat",
        "rating": 4.1,
        "reviews_count": 920,
        "price_per_night_pkr": 6800,
        "image_url": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "description": "Centrally located budget hotel in Kalam bazaar with river views, clean rooms, and hot water.",
        "highlight": "Heart of Kalam Bazaar",
        "amenities": ["Hot Water", "River View", "Free Parking", "Restaurant Onsite"],
        "website": "https://goldenstarhotelkalam.pk",
        "phone": "+92 946 812234",
    },

    # ─────────────────────────────────────────────────────────────────────────
    # ── MURREE / BHURBAN / GALIYAT (8 Verified Stays) ──
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "fallback_mre_pc",
        "name": "Pearl Continental Hotel Bhurban",
        "category": "luxury",
        "badge_label": "5-Star Luxury",
        "latitude": 33.9554,
        "longitude": 73.4526,
        "city": "Murree",
        "short_address": "Bhurban Heights",
        "full_address": "Murree Hills, Bhurban, Khyber Pakhtunkhwa, 47150",
        "address": "Murree Hills, Bhurban",
        "rating": 4.7,
        "reviews_count": 6200,
        "price_per_night_pkr": 56000,
        "image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
        "description": "World-famous 5-star mountain resort perched on cliffside terraces with golf course and Kashmir views.",
        "highlight": "Cliffside Bhurban Golf Resort",
        "amenities": ["Mountain / Valley View", "Swimming Pool", "Spa & Wellness Center", "Fine Dining Restaurant", "Complimentary Breakfast", "Free Secure Parking"],
        "website": "https://www.pchotels.com/hotel/pearl-continental-hotel-bhurban",
        "phone": "+92 51 3355700",
    },
    {
        "id": "fallback_mre_chinar",
        "name": "Chinar Family Resort Murree",
        "category": "resort",
        "badge_label": "Mountain Resort",
        "latitude": 33.9100,
        "longitude": 73.3950,
        "city": "Murree",
        "short_address": "Kuldana Chowk, Murree",
        "full_address": "Kuldana Rd, Murree Hills, Rawalpindi",
        "address": "Kuldana Rd, Murree",
        "rating": 4.4,
        "reviews_count": 1600,
        "price_per_night_pkr": 19000,
        "image_url": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
        "description": "Cozy alpine pine resort with children's play areas, lawn bonfires, and direct access to Mall Road.",
        "highlight": "Alpine Pine Grove",
        "amenities": ["Mountain / Valley View", "Complimentary Breakfast", "Evening Bonfire Area", "Free Secure Parking", "Central Heating & AC"],
        "website": "https://chinarresort.pk",
        "phone": "+92 51 3410500",
    },
    {
        "id": "fallback_mre_lockwood",
        "name": "Lockwood Hotel Murree",
        "category": "boutique",
        "badge_label": "Heritage Lodge",
        "latitude": 33.9050,
        "longitude": 73.3880,
        "city": "Murree",
        "short_address": "Mall Road, Murree",
        "full_address": "Mall Road, Murree Hills",
        "address": "Mall Road, Murree",
        "rating": 4.5,
        "reviews_count": 2100,
        "price_per_night_pkr": 24000,
        "image_url": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
        "description": "Historic boutique hotel dating to 1880 with vintage wooden fireplaces, British colonial architecture, and high tea.",
        "highlight": "Colonial Fireplace Lodge",
        "amenities": ["Wood Fireplaces", "Colonial Dining", "Free Wi-Fi", "Free Breakfast"],
        "website": "https://lockwoodhotel.pk",
        "phone": "+92 51 3410112",
    },
    {
        "id": "fallback_mre_glamping",
        "name": "Bhurban Treehouse & Glamping Domes",
        "category": "glamping",
        "badge_label": "Treehouse Glamping",
        "latitude": 33.9480,
        "longitude": 73.4420,
        "city": "Murree",
        "short_address": "Bhurban Pine Ridge",
        "full_address": "Bhurban Heights Nature Reserve, Murree",
        "address": "Bhurban Ridge, Murree",
        "rating": 4.7,
        "reviews_count": 680,
        "price_per_night_pkr": 22000,
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
        "description": "Elevated wooden treehouse villas nestled 30 feet above pine forest canopies with private stargazing hot tubs.",
        "highlight": "Canopy Treehouse & Hot Tub",
        "amenities": ["Private Hot Tub", "Canopy Pine Views", "Bonfire Pit", "Breakfast in Bed"],
        "website": "https://bhurbantreehouse.pk",
        "phone": "+92 300 9871234",
    },
    {
        "id": "fallback_mre_budget",
        "name": "Brightlands Hotel Murree",
        "category": "budget",
        "badge_label": "Budget Alpine Stay",
        "latitude": 33.9020,
        "longitude": 73.3850,
        "city": "Murree",
        "short_address": "Upper Mall Road",
        "full_address": "Upper Mall Road, Murree",
        "address": "Upper Mall, Murree",
        "rating": 4.2,
        "reviews_count": 1150,
        "price_per_night_pkr": 8500,
        "image_url": "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
        "description": "Popular family budget choice on peaceful Upper Mall with sweeping mountain views and central heating.",
        "highlight": "Upper Mall Tranquility",
        "amenities": ["Mountain View", "Central Heating", "Free Wi-Fi", "Free Parking"],
        "website": "https://brightlandshotel.pk",
        "phone": "+92 51 3410280",
    },
]


def get_curated_fallback_stays(
    city_name: Optional[str] = None,
    category: Optional[str] = "all",
    origin_lat: Optional[float] = None,
    origin_lon: Optional[float] = None,
    search_lat: Optional[float] = None,
    search_lon: Optional[float] = None,
    radius_km: float = 40.0,
) -> List[StayItem]:
    """
    Returns verified real Pakistani accommodations strictly bounded to the target city/coordinates.
    Never leaks distant stays (e.g. searching Islamabad will never return Hunza or Skardu stays).
    """
    city_filter = (city_name or "").lower().strip()
    cat_filter = (category or "all").lower().strip()
    is_gps = any(k in city_filter for k in ["current location", "gps", "nearby"])

    results: List[StayItem] = []
    city_matched_items: List[Dict] = []

    for item in CURATED_HOTELS_DB:
        item_lat = item["latitude"]
        item_lon = item["longitude"]
        item_city = (item.get("city") or "").lower()

        # 1. Geographic radius check if search center provided
        if search_lat is not None and search_lon is not None:
            dist_from_search = haversine_distance_km(search_lat, search_lon, item_lat, item_lon)
            if dist_from_search > radius_km + 10.0:
                continue

        # 2. City name check if city specified and not GPS
        if not is_gps and city_filter and city_filter != "all locations":
            city_parts = [p.strip() for p in city_filter.split("/") if p.strip()]
            item_parts = [p.strip() for p in item_city.split("/") if p.strip()]
            matches_city = any(
                cp in item_city or any(ip in cp for ip in item_parts)
                for cp in city_parts
            )
            if not matches_city:
                continue

        city_matched_items.append(item)

        # 3. Category filter
        if cat_filter != "all":
            item_cat = item.get("category", "all").lower()
            if item_cat != cat_filter and not (cat_filter in ["pods", "glamping"] and item_cat in ["pods", "glamping"]):
                continue

        price = item.get("price_per_night_pkr")
        price_fmt = format_price_pkr(price)

        # Directions URL strictly from user device GPS to hotel
        if origin_lat is not None and origin_lon is not None:
            directions = f"https://www.google.com/maps/dir/?api=1&origin={origin_lat:.5f},{origin_lon:.5f}&destination={item_lat:.5f},{item_lon:.5f}&travelmode=driving"
        else:
            directions = f"https://www.google.com/maps/dir/?api=1&destination={item_lat:.5f},{item_lon:.5f}&travelmode=driving"

        stay = StayItem(
            id=item["id"],
            name=item["name"],
            category=item["category"],
            badge_label=item["badge_label"],
            description=item.get("description"),
            latitude=item_lat,
            longitude=item_lon,
            short_address=item.get("short_address", item.get("address")),
            full_address=item.get("full_address", item.get("address")),
            address=item.get("address", ""),
            city=item.get("city", "Pakistan"),
            country="Pakistan",
            rating=item.get("rating"),
            reviews_count=item.get("reviews_count"),
            price_per_night_pkr=price,
            price_formatted=price_fmt,
            is_available=True,
            image_url=item.get("image_url"),
            galleryImages=[item["image_url"]] if item.get("image_url") else [],
            website=item.get("website"),
            phone=item.get("phone"),
            highlight=item.get("highlight"),
            amenities=item.get("amenities", []),
            directions_url=directions,
        )
        results.append(stay)

    # If specific category had 0 results but the city has properties, return all properties in THAT SAME CITY
    if not results and city_matched_items:
        for item in city_matched_items:
            item_lat = item["latitude"]
            item_lon = item["longitude"]
            price = item.get("price_per_night_pkr")
            if origin_lat is not None and origin_lon is not None:
                directions = f"https://www.google.com/maps/dir/?api=1&origin={origin_lat:.5f},{origin_lon:.5f}&destination={item_lat:.5f},{item_lon:.5f}&travelmode=driving"
            else:
                directions = f"https://www.google.com/maps/dir/?api=1&destination={item_lat:.5f},{item_lon:.5f}&travelmode=driving"

            results.append(
                StayItem(
                    id=item["id"],
                    name=item["name"],
                    category=item["category"],
                    badge_label=item["badge_label"],
                    description=item.get("description"),
                    latitude=item_lat,
                    longitude=item_lon,
                    short_address=item.get("short_address", item.get("address")),
                    full_address=item.get("full_address", item.get("address")),
                    address=item.get("address", ""),
                    city=item.get("city", "Pakistan"),
                    country="Pakistan",
                    rating=item.get("rating"),
                    reviews_count=item.get("reviews_count"),
                    price_per_night_pkr=price,
                    price_formatted=format_price_pkr(price),
                    is_available=True,
                    image_url=item.get("image_url"),
                    galleryImages=[item["image_url"]] if item.get("image_url") else [],
                    website=item.get("website"),
                    phone=item.get("phone"),
                    highlight=item.get("highlight"),
                    amenities=item.get("amenities", []),
                    directions_url=directions,
                )
            )

    return results
