import 'package:flutter/material.dart';

/// Categories of trip checklist items.
enum ChecklistCategory {
  task,
  hotel,
  food,
  placesToVisit,
}

extension ChecklistCategoryExtension on ChecklistCategory {
  String get displayName {
    switch (this) {
      case ChecklistCategory.task:
        return 'Task & Note';
      case ChecklistCategory.hotel:
        return 'Hotel & Stay';
      case ChecklistCategory.food:
        return 'Food & Dining';
      case ChecklistCategory.placesToVisit:
        return 'Places to Visit';
    }
  }

  String get originTag {
    switch (this) {
      case ChecklistCategory.task:
        return 'Task';
      case ChecklistCategory.hotel:
        return 'Hotel';
      case ChecklistCategory.food:
        return 'Food';
      case ChecklistCategory.placesToVisit:
        return 'Places to Visit';
    }
  }

  IconData get icon {
    switch (this) {
      case ChecklistCategory.task:
        return Icons.task_alt_rounded;
      case ChecklistCategory.hotel:
        return Icons.hotel_rounded;
      case ChecklistCategory.food:
        return Icons.restaurant_rounded;
      case ChecklistCategory.placesToVisit:
        return Icons.place_rounded;
    }
  }

  Color get color {
    switch (this) {
      case ChecklistCategory.task:
        return const Color(0xFF5A7328);
      case ChecklistCategory.hotel:
        return const Color(0xFF0288D1);
      case ChecklistCategory.food:
        return const Color(0xFFE65100);
      case ChecklistCategory.placesToVisit:
        return const Color(0xFF7B1FA2);
    }
  }
}

/// Represents an individual item in the user's plan-aware trip checklist.
class TripChecklistItem {
  final String id;
  final String planId;
  final String title;
  final ChecklistCategory category;
  final String? customTag;
  final String? referenceId;
  final int? dayNumber; // 1-based day index (1 = Day 1), null = General / Trip-wide
  final String? dayTitle; // e.g. "Islamabad ➔ Naran"
  final bool isCompleted;
  final DateTime createdAt;
  final DateTime updatedAt;

  TripChecklistItem({
    required this.id,
    required this.planId,
    required this.title,
    required this.category,
    this.customTag,
    this.referenceId,
    this.dayNumber,
    this.dayTitle,
    this.isCompleted = false,
    DateTime? createdAt,
    DateTime? updatedAt,
  })  : createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();

  String get originTag => displayTag;
  IconData get originIcon => displayIcon;
  Color get originColor => displayColor;

  /// Dynamic tag resolving according to category or content generated by chatbot.
  String get displayTag {
    if (customTag != null && customTag!.trim().isNotEmpty) {
      return customTag!.trim();
    }
    if (category == ChecklistCategory.placesToVisit) {
      return 'Places to Visit';
    }
    if (category == ChecklistCategory.hotel) {
      return 'Hotel';
    }
    if (category == ChecklistCategory.food) {
      return 'Food';
    }
    return inferTagFromContent(title);
  }

  IconData get displayIcon {
    final tag = displayTag.toLowerCase();
    if (tag.contains('place') || tag.contains('visit')) {
      return Icons.place_rounded;
    }
    if (tag.contains('hotel') || tag.contains('stay') || tag.contains('resort')) {
      return Icons.hotel_rounded;
    }
    if (tag.contains('food') || tag.contains('dining') || tag.contains('restaurant')) {
      return Icons.restaurant_rounded;
    }
    if (tag.contains('pack')) {
      return Icons.backpack_rounded;
    }
    if (tag.contains('photo') || tag.contains('camera')) {
      return Icons.camera_alt_rounded;
    }
    if (tag.contains('prep') || tag.contains('ticket') || tag.contains('permit')) {
      return Icons.confirmation_number_rounded;
    }
    return Icons.task_alt_rounded;
  }

  Color get displayColor {
    final tag = displayTag.toLowerCase();
    if (tag.contains('place') || tag.contains('visit')) {
      return const Color(0xFF7B1FA2);
    }
    if (tag.contains('hotel') || tag.contains('stay') || tag.contains('resort')) {
      return const Color(0xFF0288D1);
    }
    if (tag.contains('food') || tag.contains('dining') || tag.contains('restaurant')) {
      return const Color(0xFFE65100);
    }
    if (tag.contains('pack')) {
      return const Color(0xFF00897B);
    }
    if (tag.contains('photo') || tag.contains('camera')) {
      return const Color(0xFFC2185B);
    }
    if (tag.contains('prep') || tag.contains('ticket') || tag.contains('permit')) {
      return const Color(0xFF5D4037);
    }
    return const Color(0xFF5A7328);
  }

  static String inferTagFromContent(String content) {
    final lower = content.toLowerCase();
    if (lower.contains('hotel') ||
        lower.contains('resort') ||
        lower.contains('stay') ||
        lower.contains('lodge') ||
        lower.contains('guest house') ||
        lower.contains('inn') ||
        lower.contains('motel')) {
      return 'Hotel';
    }
    if (lower.contains('food') ||
        lower.contains('restaurant') ||
        lower.contains('dining') ||
        lower.contains('dinner') ||
        lower.contains('lunch') ||
        lower.contains('breakfast') ||
        lower.contains('cafe') ||
        lower.contains('tea') ||
        lower.contains('trout') ||
        lower.contains('karahi') ||
        lower.contains('bbq') ||
        lower.contains('biryani') ||
        lower.contains('snack') ||
        lower.contains('meal')) {
      return 'Food';
    }
    if (lower.contains('visit') ||
        lower.contains('lake') ||
        lower.contains('fort') ||
        lower.contains('valley') ||
        lower.contains('pass') ||
        lower.contains('glacier') ||
        lower.contains('bazaar') ||
        lower.contains('museum') ||
        lower.contains('monument') ||
        lower.contains('waterfall') ||
        lower.contains('viewpoint') ||
        lower.contains('explore') ||
        lower.contains('hike') ||
        lower.contains('trek') ||
        lower.contains('boating') ||
        lower.contains('bridge') ||
        lower.contains('meadows') ||
        lower.contains('sightseeing')) {
      return 'Places to Visit';
    }
    if (lower.contains('pack') ||
        lower.contains('jacket') ||
        lower.contains('boots') ||
        lower.contains('clothes') ||
        lower.contains('shoes') ||
        lower.contains('kit') ||
        lower.contains('medicine') ||
        lower.contains('first aid') ||
        lower.contains('charger') ||
        lower.contains('power bank') ||
        lower.contains('powerbank')) {
      return 'Packing';
    }
    if (lower.contains('photo') ||
        lower.contains('camera') ||
        lower.contains('drone') ||
        lower.contains('stargazing')) {
      return 'Photography';
    }
    if (lower.contains('ticket') ||
        lower.contains('permit') ||
        lower.contains('passport') ||
        lower.contains('cnic') ||
        lower.contains('booking') ||
        lower.contains('cash') ||
        lower.contains('atm')) {
      return 'Travel Prep';
    }
    return 'Task';
  }

  TripChecklistItem copyWith({
    String? id,
    String? planId,
    String? title,
    ChecklistCategory? category,
    String? customTag,
    String? referenceId,
    int? dayNumber,
    String? dayTitle,
    bool? isCompleted,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return TripChecklistItem(
      id: id ?? this.id,
      planId: planId ?? this.planId,
      title: title ?? this.title,
      category: category ?? this.category,
      customTag: customTag ?? this.customTag,
      referenceId: referenceId ?? this.referenceId,
      dayNumber: dayNumber ?? this.dayNumber,
      dayTitle: dayTitle ?? this.dayTitle,
      isCompleted: isCompleted ?? this.isCompleted,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'plan_id': planId,
      'title': title,
      'category': category.name,
      'custom_tag': customTag,
      'reference_id': referenceId,
      'day_number': dayNumber,
      'day_title': dayTitle,
      'is_completed': isCompleted ? 1 : 0,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  factory TripChecklistItem.fromMap(Map<String, dynamic> map) {
    return TripChecklistItem(
      id: map['id'] as String,
      planId: map['plan_id'] as String,
      title: map['title'] as String,
      category: _parseCategory(map['category'] as String?),
      customTag: map['custom_tag'] as String?,
      referenceId: map['reference_id'] as String?,
      dayNumber: map['day_number'] as int?,
      dayTitle: map['day_title'] as String?,
      isCompleted: (map['is_completed'] == 1 || map['is_completed'] == true),
      createdAt: map['created_at'] != null
          ? DateTime.tryParse(map['created_at'] as String) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: map['updated_at'] != null
          ? DateTime.tryParse(map['updated_at'] as String) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => toMap();

  factory TripChecklistItem.fromJson(Map<String, dynamic> json) =>
      TripChecklistItem.fromMap(json);

  static ChecklistCategory _parseCategory(String? raw) {
    if (raw == null) return ChecklistCategory.task;
    final lower = raw.toLowerCase().trim();
    if (lower == 'plan' ||
        lower == 'placestovisit' ||
        lower == 'places_to_visit' ||
        lower == 'places to visit') {
      return ChecklistCategory.placesToVisit;
    }
    if (lower == 'hotel') return ChecklistCategory.hotel;
    if (lower == 'food') return ChecklistCategory.food;
    if (lower == 'task') return ChecklistCategory.task;
    return ChecklistCategory.values.firstWhere(
      (c) => c.name.toLowerCase() == lower,
      orElse: () => ChecklistCategory.task,
    );
  }
}
